### PR TITLE
New helper to stay under rate-limits policies of consumed third-parties.

### PR DESCRIPTION
**Pull request by tristan0x**
It also provides `docido_sdk.toolbox.loader.resolve_name` that allows
you load referenced Python code in YAML configuration very easily.

### CODE REVIEW

**Comment by tristan0x** [comment]
@tuxnco unit-tests are a little bit cumbersome but take a look at `test_rate_limiter.yml` that shows you how rate-limit policies can be described.

**Comment by tristan0x** [comment]
ping @tuxnco can you please review?

**Comment by tuxnco** [comment]
@tristan0x sorry for the delay, here is my review:

The proposed design is beautiful and powerful. From my understanding, it allows us to cover a broad variety of use cases:
- Contextual counters / limiters
- Stacked limiters (e.g. amount of qps per IP + overall QPS per day or whatever), which is brilliant

I have a few concerns, though:
- blocking mode: if `waits=True`, return of `__call__` should be ignored (by design, or could be `None` ?) May be the wait mode should just be a wrapper around `__call__` performing the wait, no return value expected.
- RateLimiter: I can't figure out how race conditions are prevented : if several threads call a given instance, we might end up having `self.count > self.__calls_per_window`, which is not desired.
- RateLimiter: Having the `window_size` expressed in seconds complicates everything. Maybe configured window size could be expressed in seconds, the internal `window` and `__window_size` expressed in milliseconds, and eax expressed in seconds. So that user oriented numbers are human readable / understandable, and amounts involved in computations are in the same unit, avoiding `* 1e3 / 1e3` here and there.
- RateLimiterPersistence : I have a concern with the proposed URI construction. This could simply be callable (with your impl as a default). For instance, a user using columns in context's keys could end up sharing his counter with someone else.
- RateLimiterPersistence: from my point of view, the persistence can not be handled the way it is actually : we save unconditionnally, like if the given instance is the only one with write access to the persistence layer. I think the rate limiter should be loaded at each call, and save operations should check for concurrent modification, and potentially reject the call, or retry by reloading / merging state. Things can get complicated here, not sure that's the best place to handle this.
- RateLimiterPersistence: a key retention or expiration mechanism should be available. Ideally we can bind that to the store used to handle the persistence (Redis has expiring keys, MongoDB has TTL indexes, ...)

What do you think of this : http://redis.io/commands/INCR#pattern-rate-limiter-1

**Comment by phildav** [comment]
If I understand well, each RateLimiter instance has a single bucket. Would it make sense to have RateLimiters for multiple buckets for your use case ?
For instance all twitter API points that have the same rate limit could use the same RateLimiter where each bucket is `<user> + <end point>`. And each bucket has its own windows of course.
This way you can keep the number of instances of RateLimiter low when you have a large number of `<user> + <end point>`. The storage and persistence can be optimized as well.

I'm just asking if it's interesting here or not.

**Comment by tristan0x** [comment]
Thank you Tanguy for your comment.
- You are absolutely right about the race conditions here. This first version of this rate limiter is client-side and only works in a single-thread context. The only persistence layer available to crawlers is thru the `get_kv` `set_kv` methods `IndexAPI`, which does not not provide consistency. So, for now, we are screwed.
- I didn't want to save the context at each call to `__call__` in the first place. But then, I realised number of calls made is not something you can to forget in case something goes bad afterward. Your programs made a certain amount of API calls, whether your process will raises an exception later or not.
- I agree we need to provide consist time units to the customer. I will look after that.
- I agree the returned value of `__call__(waits=True)` is purely informative, and tells the caller how long it blocks in the method. Do you think if can be confusive?
- Regarding the key computation, I think all the information should remain in the YAML configuration. If the hash method is the customer's responsibility, you can be sure there will be conflicts somehow. If you think of the rate-limiter as a service, the hash method is definitely private. It is the responsibility of the API that there won't have any conflict between 2 customers.

I already submitted the link you share in the `TellMeWhen` technical specification page. So I could not agree more :)

**Comment by tristan0x** [comment]
@phildav What you mean it to provide a context used to build the key when using a `RateLimiter` instance, in `__call__` ?

For instance:

YAML configuration:

``` yaml
rate_limits:
  twitter:
    persistence: docido_sdk.toolbox.rate_limits.IndexAPIRLPersistence
    window_size_sec: 1
    calls_per_window: 5
    key:
        - docido
        - twitter
        - "{user}"
        - "{stream_id}"
```

And then use it this way:

``` python
api = get_twitter_api(user='john.doe')
john_doe_rl = get_rate_limiter("twitter", user='john-doe')

john_doe_rl(stream_id=4242)
api.read_stream(id=4242)

john_doe_rl(stream_id=4243)
api.read_stream(id=4243)
```

If so I think it is brilliant !

**Pull request merged**
